name = "laguer-web"
main = "functions/api/[[path]].js"
compatibility_date = "2024-07-01"

[[d1_databases]]
binding = "DB"
database_name = "laguer-db"
database_id = "4861481c-4cd3-4c09-8820-8e6e93d10f3a"